import feedparser
import os
import time
import requests
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

# --- CONFIGURATION ---
# UPDATED SEARCH QUERY:
# Added keywords: "report", "publication", "outlook", "earnings", "profit", "result", "quarter", "Q3", "Q4"
RSS_FEED_URL = "https://news.google.com/rss/search?q=(NBFC+OR+Banking)+AND+(investment+OR+deal+OR+funding+OR+stake+OR+partnership+OR+tie-up+OR+launch+OR+product+OR+appoint+OR+CEO+OR+report+OR+publication+OR+outlook+OR+earnings+OR+profit+OR+result+OR+quarter)+AND+India+when:1d&hl=en-IN&gl=IN&ceid=IN:en"

# Priority Models
MODELS = [
    "gemini-2.5-flash",
    "gemini-2.5-flash-lite", 
    "gemini-3.0-pro-preview",
    "gemini-2.0-flash"
]

# API Keys & Secrets
API_KEY = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
EMAIL_USER = os.environ.get("EMAIL_USER")
EMAIL_PASS = os.environ.get("EMAIL_PASS")
EMAIL_RECEIVER = os.environ.get("EMAIL_RECEIVER")

def send_email(content):
    if not EMAIL_USER or not EMAIL_PASS or not EMAIL_RECEIVER:
        print("Skipping email: Missing EMAIL_USER, EMAIL_PASS, or EMAIL_RECEIVER secrets.")
        return

    try:
        msg = MIMEMultipart()
        msg['From'] = EMAIL_USER
        msg['To'] = EMAIL_RECEIVER
        msg['Subject'] = f"MD's Daily Briefing: India NBFC & Banking - {datetime.now().strftime('%d %b %Y')}"

        # Clean Professional HTML Format
        html_content = f"""
        <html>
        <body style="font-family: 'Segoe UI', Arial, sans-serif; color: #333; line-height: 1.6;">
            <div style="max-width: 650px; margin: auto; border: 1px solid #ddd; padding: 20px; border-radius: 8px;">
                <h2 style="color: #004080; border-bottom: 2px solid #004080; padding-bottom: 10px;">
                    🇮🇳 MD's Daily Intelligence Briefing
                </h2>
                <p style="font-size: 13px; color: #666;">
                    <strong>Date:</strong> {datetime.now().strftime('%d %B %Y')}<br>
                    <strong>Coverage:</strong> Deals, Earnings, Strategy, & Reports
                </p>
                <div style="background-color: #f9f9f9; padding: 15px; border-radius: 5px;">
                    {content.replace('\n', '<br>')} 
                </div>
                <p style="font-size: 11px; color: #888; margin-top: 20px;">
                    Generated by Gemini 2.5 Bot | India Market Focus
                </p>
            </div>
        </body>
        </html>
        """
        msg.attach(MIMEText(html_content, 'html'))

        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(EMAIL_USER, EMAIL_PASS)
        server.send_message(msg)
        server.quit()
        
        print(f"✅ Executive Briefing sent to {EMAIL_RECEIVER}!")
    except Exception as e:
        print(f"❌ Failed to send email: {e}")

def analyze_market_news():
    print("Fetching India NBFC ecosystem news (Earnings, Reports, Deals)...")
    
    feed = feedparser.parse(RSS_FEED_URL)
    headlines = []
    # Increased to 25 to capture earnings which often come in bulk
    for entry in feed.entries[:25]:
        headlines.append(f"- {entry.title} (Link: {entry.link})")

    if not headlines:
        print("No news found today.")
        return

    print(f"Found {len(headlines)} headlines. Preparing Executive Briefing...")

    if not API_KEY:
        print("Error: API Key is missing.")
        return

    # --- THE "MD BRIEFING" PROMPT (UPDATED) ---
    prompt_text = (
        "You are the Executive Assistant to the Managing Director of a leading Indian NBFC. "
        "Review today's news and create a high-level intelligence briefing. "
        "Focus ONLY on the Indian market.\n\n"
        
        "Categorize the news into these 6 strategic buckets:\n"
        "1. **📊 Earnings & Financial Performance:** (Quarterly Results, Profit/Loss, AUM Growth, NPA updates). *Include Key Figures.*\n"
        "2. **💰 Deals & Fundraising:** (Capital Raise, M&A, Stake Sales). *Include Deal Value.*\n"
        "3. **📑 Reports & Publications:** (New Industry Reports, Whitepapers, Outlooks by CRISIL, ICRA, RBI, etc.). **IMPORTANT: You MUST include the (Link) provided in the headline so the MD can read it.**\n"
        "4. **🤝 Strategic Partnerships:** (Co-lending, Fintech tie-ups).\n"
        "5. **🚀 New Launches & Strategy:** (New Products, Expansions, Business Pivots).\n"
        "6. **👔 Leadership & Regulation:** (CEO/CXO Moves, RBI/SEBI Circulars).\n\n"

        "**Headlines:**\n"
        + "\n".join(headlines) + "\n\n"

        "**Output Instructions:**\n"
        "- **Tone:** Executive, concise, data-driven.\n"
        "- **Earnings:** Highlight Net Profit (PAT) and Asset Quality (NPA) if mentioned.\n"
        "- **Links:** For 'Reports' and 'Earnings', append the clickable link at the end of the bullet point like this: [Read Source].\n"
        "- If a category has no relevant news, omit it.\n"
        "- **Format:** Use HTML-friendly markdown (Bold headers, bullet points).\n"
    )

    # --- THE DIRECT API LOOP ---
    success = False
    final_report = ""

    for model in MODELS:
        print(f"Attempting direct connection to: {model}...")
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={API_KEY}"
        headers = {'Content-Type': 'application/json'}
        data = {"contents": [{"parts": [{"text": prompt_text}]}]}

        try:
            response = requests.post(url, headers=headers, json=data, timeout=30)
            
            if response.status_code == 200:
                result = response.json()
                try:
                    text_output = result['candidates'][0]['content']['parts'][0]['text']
                    print("\n" + "="*30)
                    print(f"SUCCESS with {model}")
                    print("="*30)
                    print(text_output)
                    print("="*30)
                    
                    final_report = text_output
                    success = True
                    break 
                except (KeyError, IndexError):
                    print(f"Model {model} returned 200 OK but unreadable format.")
                    continue
            elif response.status_code == 429:
                print(f"Model {model} is busy (Quota Exceeded). Trying next...")
                time.sleep(1)
            elif response.status_code == 404:
                print(f"Model {model} not found. Trying next...")
            else:
                print(f"Model {model} failed with Status {response.status_code}")

        except Exception as e:
            print(f"Connection error with {model}: {e}")

    if success:
        send_email(final_report)
    else:
        print("CRITICAL: All models failed. No email sent.")

if __name__ == "__main__":
    analyze_market_news()
