import feedparser
import os
import time
import requests
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

# --- CONFIGURATION ---
RSS_FEED_URL = "https://news.google.com/rss/search?q=(NBFC+OR+Banking)+AND+(investment+OR+deal+OR+funding+OR+acquisition+OR+merger+OR+stake)&hl=en-IN&gl=IN&ceid=IN:en"

# Priority Models (Gemini 2.5 & 3.0)
MODELS = [
    "gemini-2.5-flash",
    "gemini-2.5-flash-lite", 
    "gemini-3.0-pro-preview",
    "gemini-2.0-flash"
]

# API Keys & Secrets
API_KEY = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
EMAIL_USER = os.environ.get("EMAIL_USER")
EMAIL_PASS = os.environ.get("EMAIL_PASS")
EMAIL_RECEIVER = os.environ.get("EMAIL_RECEIVER")

def send_email(content):
    if not EMAIL_USER or not EMAIL_PASS or not EMAIL_RECEIVER:
        print("Skipping email: Missing EMAIL_USER, EMAIL_PASS, or EMAIL_RECEIVER secrets.")
        return

    try:
        msg = MIMEMultipart()
        msg['From'] = EMAIL_USER
        msg['To'] = EMAIL_RECEIVER
        msg['Subject'] = f"NBFC & Banking Deal Report - {datetime.now().strftime('%Y-%m-%d')}"

        # Convert Markdown to simple HTML for better reading
        html_content = f"""
        <html>
        <body>
            <h2>Daily Financial Intelligence</h2>
            <pre style="font-family: Arial, sans-serif; white-space: pre-wrap;">{content}</pre>
            <p><em>Generated by Gemini 2.5/3.0 Bot</em></p>
        </body>
        </html>
        """
        msg.attach(MIMEText(html_content, 'html'))

        # Connect to Gmail SMTP (Change if using Outlook/Yahoo)
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(EMAIL_USER, EMAIL_PASS)
        server.send_message(msg)
        server.quit()
        
        print(f"✅ Email successfully sent to {EMAIL_RECEIVER}!")
    except Exception as e:
        print(f"❌ Failed to send email: {e}")

def analyze_market_news():
    print("Fetching NBFC & Banking Deal news...")
    
    feed = feedparser.parse(RSS_FEED_URL)
    headlines = []
    for entry in feed.entries[:10]:
        headlines.append(f"- {entry.title}")

    if not headlines:
        print("No specific deal news found today.")
        return

    print(f"Found {len(headlines)} headlines. Sending to AI for analysis...")

    if not API_KEY:
        print("Error: API Key is missing.")
        return

    prompt_text = (
        "You are a financial analyst. Review these news headlines about NBFCs and Banking.\n"
        "Identify and summarize ONLY:\n"
        "1. New Investments (Who invested in whom?)\n"
        "2. Mergers & Acquisitions (Deals)\n"
        "3. Major Regulatory Updates affecting the sector\n\n"
        "Headlines:\n"
        + "\n".join(headlines) + "\n\n"
        "Output Format:\n"
        "- **Deals & Investments:** [List details]\n"
        "- **Top Sector News:** [Major non-deal updates]\n"
        "If nothing relevant is found in a category, write 'None'."
    )

    # --- THE DIRECT API LOOP ---
    success = False
    final_report = ""

    for model in MODELS:
        print(f"Attempting direct connection to: {model}...")
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={API_KEY}"
        headers = {'Content-Type': 'application/json'}
        data = {"contents": [{"parts": [{"text": prompt_text}]}]}

        try:
            response = requests.post(url, headers=headers, json=data, timeout=30)
            
            if response.status_code == 200:
                result = response.json()
                try:
                    text_output = result['candidates'][0]['content']['parts'][0]['text']
                    print("\n" + "="*30)
                    print(f"SUCCESS with {model}")
                    print("="*30)
                    print(text_output)
                    print("="*30)
                    
                    final_report = text_output # Save for email
                    success = True
                    break 
                except (KeyError, IndexError):
                    print(f"Model {model} returned 200 OK but unreadable format.")
                    continue
            elif response.status_code == 429:
                print(f"Model {model} is busy (Quota Exceeded). Trying next...")
                time.sleep(1)
            elif response.status_code == 404:
                print(f"Model {model} not found. Trying next...")
            else:
                print(f"Model {model} failed with Status {response.status_code}")

        except Exception as e:
            print(f"Connection error with {model}: {e}")

    # --- SEND EMAIL IF SUCCESSFUL ---
    if success:
        send_email(final_report)
    else:
        print("CRITICAL: All models failed. No email sent.")

if __name__ == "__main__":
    analyze_market_news()
